# Generated by Django 3.0.5 on 2021-09-20 08:50

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
        ('licenses', '0002_auto_20210920_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=250)),
                ('private', models.BooleanField()),
                ('html_url', models.URLField()),
                ('description', models.TextField()),
                ('language', models.CharField(blank=True, max_length=250, null=True)),
                ('forks_count', models.IntegerField()),
                ('size', models.IntegerField()),
                ('is_template', models.BooleanField()),
                ('pushed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.NOT_PROVIDED, related_name='repositories', to='licenses.Licence', verbose_name='Licence')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='owners.Owner', verbose_name='Owner')),
                ('template_repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='repositories.Repository', verbose_name='Repository')),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
    ]
