# Generated by Django 3.0.5 on 2021-09-16 15:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('full_name', models.CharField(max_length=250, unique=True)),
                ('private', models.BooleanField()),
                ('html_url', models.URLField()),
                ('description', models.TextField()),
                ('fork', models.BooleanField()),
                ('language', models.CharField(max_length=250)),
                ('forks_count', models.IntegerField()),
                ('stargazers_count', models.IntegerField()),
                ('watchers_count', models.IntegerField()),
                ('size', models.IntegerField()),
                ('open_issues_count', models.IntegerField()),
                ('is_template', models.BooleanField()),
                ('has_issues', models.BooleanField()),
                ('has_projects', models.BooleanField()),
                ('has_wiki', models.BooleanField()),
                ('has_pages', models.BooleanField()),
                ('has_downloads', models.BooleanField()),
                ('archived', models.BooleanField()),
                ('disabled', models.BooleanField()),
                ('pushed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('allow_rebase_merge', models.BooleanField()),
                ('allow_squash_merge', models.BooleanField()),
                ('allow_auto_merge', models.BooleanField()),
                ('delete_branch_on_merge', models.BooleanField()),
                ('allow_merge_commit', models.BooleanField()),
                ('subscribers_count', models.IntegerField()),
                ('network_count', models.IntegerField()),
                ('license', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, related_name='repositories', to='licenses.Licence', verbose_name='Licence')),
                ('template_repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='repositories.Repository', verbose_name='Repository')),
            ],
        ),
    ]
