# Generated by Django 3.0.5 on 2021-09-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='allow_auto_merge',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='allow_merge_commit',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='allow_rebase_merge',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='allow_squash_merge',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='delete_branch_on_merge',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='disabled',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='fork',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='has_downloads',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='has_issues',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='has_pages',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='has_projects',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='has_wiki',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='network_count',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='open_issues_count',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='stargazers_count',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='subscribers_count',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='watchers_count',
        ),
    ]
