# Generated by Django 3.0.5 on 2021-09-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0004_auto_20210917_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='full_name',
            field=models.CharField(max_length=250),
        ),
    ]
