# Generated by Django 3.0.5 on 2021-09-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='key',
            field=models.SlugField(unique=True),
        ),
    ]
